package com.kyronic.riskengine.riskregister.interfaces;

import com.kyronic.riskengine.common.api.ApiResponse;
import com.kyronic.riskengine.riskregister.application.dto.RiskRecordRequest;
import com.kyronic.riskengine.riskregister.application.dto.RiskRecordResponse;
import com.kyronic.riskengine.riskregister.application.service.RiskRegisterService;
import com.kyronic.riskengine.riskregister.infrastructure.configuration.RiskRegisterOpenApiConfiguration;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/v1/risk-register/risks")
@Tag(name = "Risk Register", description = "Comprehensive CRUD endpoints for risk register records.")
@SecurityRequirement(name = RiskRegisterOpenApiConfiguration.BEARER_SCHEME)
public class RiskRecordController {

    private final RiskRegisterService riskRegisterService;

    public RiskRecordController(RiskRegisterService riskRegisterService) {
        this.riskRegisterService = riskRegisterService;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Create risk record", description = "Capture a new risk register record. The risk identifier is generated by the backend.")
    public ApiResponse<RiskRecordResponse> create(@Valid @RequestBody RiskRecordRequest request) {
        return ApiResponse.success("Risk record created successfully", riskRegisterService.create(request), null);
    }

    @GetMapping
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "List risk records", description = "Fetch all active risk register records.")
    public ApiResponse<List<RiskRecordResponse>> list() {
        return ApiResponse.success("Risk records retrieved successfully", riskRegisterService.list(), null);
    }

    @GetMapping("/{riskId}")
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Get risk record", description = "Fetch a single risk register record by its system-generated risk identifier.")
    public ApiResponse<RiskRecordResponse> get(@PathVariable("riskId") String riskId) {
        return ApiResponse.success("Risk record retrieved successfully", riskRegisterService.get(riskId), null);
    }

    @PutMapping("/{riskId}")
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Update risk record", description = "Update a captured risk register record by its system-generated risk identifier.")
    public ApiResponse<RiskRecordResponse> update(@PathVariable("riskId") String riskId,
                                                  @Valid @RequestBody RiskRecordRequest request) {
        return ApiResponse.success("Risk record updated successfully", riskRegisterService.update(riskId, request), null);
    }

    @DeleteMapping("/{riskId}")
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Delete risk record", description = "Soft delete a captured risk register record by its system-generated risk identifier.")
    public ApiResponse<Void> delete(@PathVariable("riskId") String riskId) {
        riskRegisterService.delete(riskId);
        return ApiResponse.success("Risk record deleted successfully", null, null);
    }
}
