server:
  port: 8088
spring:
  application:
    name: risk-register-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
kyronic:
  audit:
    service-url: http://localhost:8083
