create schema if not exists process_flows_service;

create sequence if not exists process_flows_service.process_flow_reference_seq start with 1 increment by 1;

create table if not exists process_flows_service.process_flows (
    id bigint generated by default as identity primary key,
    flow_reference varchar(32) not null unique,
    name varchar(180) not null,
    department_id bigint not null,
    process_owner varchar(120) not null,
    status varchar(80) not null,
    description varchar(4000),
    created_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_at timestamp with time zone not null,
    updated_by varchar(120) not null,
    version bigint
);

create index if not exists idx_process_flows_created_at on process_flows_service.process_flows (created_at desc);
create index if not exists idx_process_flows_department on process_flows_service.process_flows (department_id);
create index if not exists idx_process_flows_status on process_flows_service.process_flows (status);
