server:
  port: 8087
spring:
  application:
    name: kri-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
kyronic:
  audit:
    service-url: http://localhost:8083
