create schema if not exists self_assessment_service;

create sequence if not exists self_assessment_service.rcsa_reference_seq start with 1 increment by 1;

create table if not exists self_assessment_service.self_assessments (
    id bigint generated by default as identity primary key,
    rcsa_id varchar(32) not null unique,
    assessment_period varchar(80) not null,
    department_id bigint not null,
    process_name varchar(180) not null,
    risk_register_risk varchar(120) not null,
    risk_scenario varchar(4000) not null,
    cause varchar(2000) not null,
    consequence_impact varchar(2000) not null,
    inherent_impact integer not null,
    inherent_likelihood integer not null,
    inherent_risk_score integer not null,
    inherent_risk_rating varchar(40) not null,
    control_design_effectiveness varchar(120) not null,
    control_operating_effectiveness varchar(120) not null,
    overall_control_effectiveness varchar(120) not null,
    residual_impact integer not null,
    residual_likelihood integer not null,
    residual_risk_score integer not null,
    residual_risk_rating varchar(40) not null,
    risk_response varchar(120) not null,
    action_required boolean not null,
    linked_action varchar(500),
    business_review_status varchar(80) not null,
    risk_review_verification varchar(120) not null,
    risk_review_comment varchar(2000),
    date_of_last_review date,
    next_review_date date,
    created_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_at timestamp with time zone not null,
    updated_by varchar(120) not null,
    version bigint
);

create table if not exists self_assessment_service.self_assessment_linked_controls (
    self_assessment_id bigint not null references self_assessment_service.self_assessments(id) on delete cascade,
    control_reference varchar(120) not null
);

create table if not exists self_assessment_service.self_assessment_linked_kri (
    self_assessment_id bigint not null references self_assessment_service.self_assessments(id) on delete cascade,
    kri_reference varchar(120) not null
);

create table if not exists self_assessment_service.self_assessment_linked_olts (
    self_assessment_id bigint not null references self_assessment_service.self_assessments(id) on delete cascade,
    olts_reference varchar(120) not null
);

create table if not exists self_assessment_service.self_assessment_linked_findings (
    self_assessment_id bigint not null references self_assessment_service.self_assessments(id) on delete cascade,
    finding_reference varchar(120) not null
);

create index if not exists idx_self_assessments_created_at on self_assessment_service.self_assessments (created_at desc);
create index if not exists idx_self_assessments_department on self_assessment_service.self_assessments (department_id);
