package com.kyronic.riskengine.kri.interfaces;

import com.kyronic.riskengine.common.api.ApiResponse;
import com.kyronic.riskengine.kri.application.dto.KriRequest;
import com.kyronic.riskengine.kri.application.dto.KriResponse;
import com.kyronic.riskengine.kri.application.service.KriService;
import com.kyronic.riskengine.kri.infrastructure.configuration.KriOpenApiConfiguration;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/v1/kri/records")
@Tag(name = "KRI", description = "Comprehensive CRUD endpoints for Key Risk Indicators.")
@SecurityRequirement(name = KriOpenApiConfiguration.BEARER_SCHEME)
public class KriController {

    private final KriService kriService;

    public KriController(KriService kriService) {
        this.kriService = kriService;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Create KRI", description = "Capture a new Key Risk Indicator. The KRI identifier is generated by the backend.")
    public ApiResponse<KriResponse> create(@Valid @RequestBody KriRequest request) {
        return ApiResponse.success("KRI created successfully", kriService.create(request), null);
    }

    @GetMapping
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "List KRIs", description = "Fetch all active KRIs.")
    public ApiResponse<List<KriResponse>> list() {
        return ApiResponse.success("KRIs retrieved successfully", kriService.list(), null);
    }

    @GetMapping("/{kriId}")
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Get KRI", description = "Fetch a single KRI by its system-generated KRI identifier.")
    public ApiResponse<KriResponse> get(@PathVariable("kriId") String kriId) {
        return ApiResponse.success("KRI retrieved successfully", kriService.get(kriId), null);
    }

    @PutMapping("/{kriId}")
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Update KRI", description = "Update a captured KRI by its system-generated KRI identifier.")
    public ApiResponse<KriResponse> update(@PathVariable("kriId") String kriId,
                                           @Valid @RequestBody KriRequest request) {
        return ApiResponse.success("KRI updated successfully", kriService.update(kriId, request), null);
    }

    @DeleteMapping("/{kriId}")
    @PreAuthorize("isAuthenticated()")
    @Operation(summary = "Delete KRI", description = "Soft delete a captured KRI by its system-generated KRI identifier.")
    public ApiResponse<Void> delete(@PathVariable("kriId") String kriId) {
        kriService.delete(kriId);
        return ApiResponse.success("KRI deleted successfully", null, null);
    }
}
