package com.kyronic.riskengine.olts.application.dto;

import com.kyronic.riskengine.common.authorization.AuthorizationStatus;
import com.kyronic.riskengine.olts.domain.model.IncidentStatus;
import com.kyronic.riskengine.olts.domain.model.Severity;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

public record IncidentResponse(
        UUID id,
        String eventId,
        String eventTitle,
        Long eventStatusId,
        LocalDate incidentDate,
        LocalDate incidentEndDate,
        LocalDate detectionDate,
        Long departmentId,
        String departmentName,
        Long branchId,
        String branchName,
        String processName,
        String productService,
        Long baselEventCategoryId,
        String eventDescription,
        String immediateActionTaken,
        Long rootCauseCategoryId,
        String rootCauseDescription,
        Long controlId,
        Boolean failedMissingControl,
        Long currencyId,
        BigDecimal grossLoss,
        BigDecimal restitutionRemediationCost,
        Long recoveryMethodId,
        BigDecimal netLoss,
        String accountingGlReference,
        Long dataSourceId,
        String nonFinancialImpactType,
        String nonFinancialImpactDetails,
        Severity overallEventSeverity,
        String correctiveAction,
        String actionOwner,
        LocalDate actionTargetDate,
        Long actionStatusId,
        Boolean preventiveControlImplemented,
        String validationEvidence,
        LocalDate closureValidationDate,
        String closureComment,
        AuthorizationStatus authorizationStatus,
        IncidentStatus status,
        String eventOwner,
        String reportedBy,
        String createdBy,
        Instant createdAt,
        String lastUpdatedBy,
        Instant lastUpdatedAt,
        Integer recordVersion
) {
}
