package com.kyronic.riskengine.notifications.domain;

public enum NotificationType {
    AUTHORIZATION_REQUIRED,
    AUTHORIZED,
    REJECTED,
    RETURNED_FOR_CORRECTION,
    INFORMATION_REQUESTED,
    RESUBMITTED,
    AUTHORIZATION_OVERDUE,
    AUTHORIZATION_ESCALATED,
    KRI_THRESHOLD_BREACHED,
    REVIEW_DUE,
    ASSIGNMENT,
    COMMENT_ADDED,
    DOCUMENT_UPLOADED,
    RECORD_CLOSED,
    RECORD_REOPENED,
    SYSTEM
}
