create table if not exists kri_service.treatment_strategies (
    id bigint generated by default as identity primary key,
    code varchar(100) not null unique,
    name varchar(255) not null,
    status varchar(50) not null,
    created_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_at timestamp with time zone not null,
    updated_by varchar(120) not null,
    version bigint
);

create index if not exists idx_treatment_strategies_name
    on kri_service.treatment_strategies (name asc);
