package com.kyronic.riskengine.olts.infrastructure.persistence.config;

public interface BaselEventCategoryConfigurationRepository extends OltsConfigurationRepository<BaselEventCategoryConfigurationEntity> {
}
