CREATE TABLE IF NOT EXISTS olts_unit_of_measure_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO olts_unit_of_measure_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('DAYS', 'Days', 'Measure duration or aging in days.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('MONTHS', 'Months', 'Measure duration or aging in months.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('PERCENT', 'Percent', 'Measure values expressed as a percentage.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;
