CREATE TABLE IF NOT EXISTS olts_kri_category_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO olts_kri_category_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('OPERATIONAL_RISK', 'Operational Risk', 'KRI category for operational risk indicators.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('COMPLIANCE_RISK', 'Compliance Risk', 'KRI category for compliance and regulatory indicators.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('FINANCIAL_RISK', 'Financial Risk', 'KRI category for financial exposure indicators.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;
