CREATE SEQUENCE IF NOT EXISTS olts_incident_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS olts_incidents (
    id UUID PRIMARY KEY,
    incident_id VARCHAR(32) NOT NULL UNIQUE,
    department_id UUID NOT NULL,
    branch_id UUID NOT NULL,
    inputter_user_id UUID NOT NULL,
    incident_date DATE NOT NULL,
    discovery_date DATE NOT NULL,
    loss_category VARCHAR(50) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    gross_loss NUMERIC(19,2) NOT NULL,
    recoveries NUMERIC(19,2) NOT NULL,
    net_loss NUMERIC(19,2) NOT NULL,
    potential_loss NUMERIC(19,2) NOT NULL,
    responsible_person_id UUID NOT NULL,
    responsible_person_name VARCHAR(255) NOT NULL,
    authorization_status VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    record_version INTEGER NOT NULL,
    active_version BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by UUID NOT NULL,
    submitted_by UUID,
    submitted_at TIMESTAMP WITH TIME ZONE,
    authorized_by UUID,
    authorized_at TIMESTAMP WITH TIME ZONE,
    last_modified_by UUID NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
