CREATE TABLE IF NOT EXISTS olts_event_status_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_basel_event_category_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_root_cause_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_currency_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_control_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO olts_event_status_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('DRAFT', 'Draft', 'Event is being prepared by the maker.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('PENDING_APPROVAL', 'Pending Approval', 'Event has been submitted for approval.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('APPROVED', 'Approved', 'Event has been approved.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('REJECTED', 'Rejected', 'Event has been rejected.', 4, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('RETURNED', 'Returned', 'Event has been returned for correction.', 5, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_basel_event_category_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('INTERNAL_FRAUD', 'Internal Fraud', 'Losses due to internal fraud.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('EXTERNAL_FRAUD', 'External Fraud', 'Losses due to external fraud.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('EMPLOYMENT_PRACTICES', 'Employment Practices', 'Losses from employment practices and workplace safety.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_root_cause_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('PROCESS_BREAKDOWN', 'Process Breakdown', 'Failure in process execution or control design.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('SYSTEM_FAILURE', 'System Failure', 'Technology or infrastructure failure.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('HUMAN_ERROR', 'Human Error', 'Mistake or omission by staff.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_currency_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('USD', 'US Dollar', 'United States Dollar.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('EUR', 'Euro', 'Euro.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('GBP', 'Pound Sterling', 'British Pound Sterling.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_control_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('CTRL-001', 'Dual Authorization', 'Dual authorization control for sensitive transactions.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('CTRL-002', 'Daily Reconciliation', 'Daily reconciliation control for suspense items.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('CTRL-003', 'Access Review', 'Periodic user access review control.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;
