CREATE TABLE IF NOT EXISTS olts_recovery_method_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_action_status_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_data_source_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_validation_result_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS olts_residual_risk_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    display_order INTEGER,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO olts_recovery_method_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('INSURANCE', 'Insurance Recovery', 'Recoveries claimed from insurance cover.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('CUSTOMER_RECOVERY', 'Customer Recovery', 'Recoveries received from customer reimbursement or recovery action.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_action_status_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('OPEN', 'Open', 'Action is open and in progress.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('COMPLETED', 'Completed', 'Action has been completed.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('OVERDUE', 'Overdue', 'Action target date has passed.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_data_source_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('MANUAL_REPORT', 'Manual Report', 'Incident was manually reported by staff.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('SYSTEM_ALERT', 'System Alert', 'Incident was detected by automated system monitoring.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_validation_result_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('PASS', 'Pass', 'Closure or evidence validation passed.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('FAIL', 'Fail', 'Closure or evidence validation failed.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;

INSERT INTO olts_residual_risk_config (code, name, description, display_order, created_by, created_at, updated_by, updated_at)
VALUES
    ('LOW', 'Low', 'Low residual risk after corrective action.', 1, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('MEDIUM', 'Medium', 'Medium residual risk after corrective action.', 2, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP),
    ('HIGH', 'High', 'High residual risk after corrective action.', 3, 1003, CURRENT_TIMESTAMP, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;
