alter table olts_incidents
    alter column loss_category drop not null,
    alter column event_type drop not null,
    alter column description drop not null,
    alter column currency_code drop not null,
    alter column recoveries drop not null,
    alter column potential_loss drop not null,
    alter column responsible_person_id drop not null,
    alter column responsible_person_name drop not null;

alter table olts_incidents
    add column if not exists event_title varchar(255),
    add column if not exists event_status_id bigint,
    add column if not exists incident_end_date date,
    add column if not exists process_name varchar(255),
    add column if not exists product_service varchar(255),
    add column if not exists basel_event_category_id bigint,
    add column if not exists immediate_action_taken varchar(4000),
    add column if not exists root_cause_category_id bigint,
    add column if not exists root_cause_description varchar(4000),
    add column if not exists control_id bigint,
    add column if not exists failed_missing_control boolean,
    add column if not exists currency_id bigint,
    add column if not exists restitution_remediation_cost numeric(19,2),
    add column if not exists recovery_method_id bigint,
    add column if not exists accounting_gl_reference varchar(255),
    add column if not exists data_source_id bigint,
    add column if not exists non_financial_impact_type varchar(255),
    add column if not exists non_financial_impact_details varchar(4000),
    add column if not exists corrective_action varchar(4000),
    add column if not exists action_owner varchar(255),
    add column if not exists action_target_date date,
    add column if not exists action_status_id bigint,
    add column if not exists preventive_control_implemented boolean,
    add column if not exists validation_evidence varchar(4000),
    add column if not exists closure_validation_date date,
    add column if not exists closure_comment varchar(4000),
    add column if not exists event_owner varchar(255),
    add column if not exists reported_by varchar(255),
    add column if not exists created_by_username varchar(255),
    add column if not exists last_updated_by_username varchar(255);

update olts_incidents
set event_title = coalesce(event_title, incident_id),
    event_status_id = coalesce(event_status_id, 0),
    process_name = coalesce(process_name, 'UNSPECIFIED'),
    product_service = coalesce(product_service, 'UNSPECIFIED'),
    basel_event_category_id = coalesce(basel_event_category_id, 0),
    root_cause_category_id = coalesce(root_cause_category_id, 0),
    failed_missing_control = coalesce(failed_missing_control, false),
    currency_id = coalesce(currency_id, 0),
    restitution_remediation_cost = coalesce(restitution_remediation_cost, 0.00),
    preventive_control_implemented = coalesce(preventive_control_implemented, false),
    created_by_username = coalesce(created_by_username, 'system'),
    last_updated_by_username = coalesce(last_updated_by_username, 'system');
