server:
  port: 8089
spring:
  application:
    name: process-flows-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
kyronic:
  audit:
    service-url: http://localhost:8083
